<?php
require_once('TCPDF-main/tcpdf.php');
include '../config/database.php';
checkAuth();

// Create custom PDF class
class SERVICE_RECORDS_PDF extends TCPDF
{
    private $filters = array();
    private $summary = array();
    
    public function setFilters($filters)
    {
        $this->filters = $filters;
    }
    
    public function setSummary($summary)
    {
        $this->summary = $summary;
    }
    
    // Page header
    public function Header()
    {
        // Logo
        // $image_file = 'images/logo.png';
        // $this->Image($image_file, 10, 10, 15, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        
        // Set font
        $this->SetFont('helvetica', 'B', 16);
        
        // Title
        $this->Cell(0, 10, 'VEHICLE SERVICE RECORDS REPORT', 0, 1, 'C');
        
        // Report info
        $this->SetFont('helvetica', '', 10);
        $this->Cell(0, 6, 'Generated on: ' . date('d-m-Y h:i A'), 0, 1, 'C');
        
        // Show applied filters
        if (!empty($this->filters)) {
            $this->Ln(2);
            $this->SetFont('helvetica', 'B', 9);
            $this->Cell(0, 6, 'APPLIED FILTERS:', 0, 1, 'L');
            
            $this->SetFont('helvetica', '', 8);
            $filter_text = '';
            foreach ($this->filters as $key => $value) {
                if (!empty($value)) {
                    $filter_text .= ucfirst(str_replace('_', ' ', $key)) . ': ' . $value . ' | ';
                }
            }
            
            if (empty($filter_text)) {
                $filter_text = 'No filters applied - Showing all records';
            } else {
                $filter_text = rtrim($filter_text, ' | ');
            }
            
            $this->MultiCell(0, 5, $filter_text, 0, 'L');
        }
        
        // Summary line
        if (!empty($this->summary)) {
            $this->SetFont('helvetica', 'B', 9);
            $this->Cell(0, 6, 'SUMMARY:', 0, 1, 'L');
            
            $this->SetFont('helvetica', '', 8);
            $summary_text = 'Total Services: ' . ($this->summary['total_services'] ?? 0) . 
                          ' | Total Cost: ' . number_format($this->summary['total_cost'] ?? 0, 2) .
                          ' | Average Cost: ' . number_format($this->summary['avg_cost'] ?? 0, 2);
            
            $this->Cell(0, 5, $summary_text, 0, 1, 'L');
        }
        
        $this->Ln(5);
        
        // // Line separator
        // $this->SetLineWidth(0.5);
        // $this->Line(10, $this->GetY(), 287, $this->GetY());
        // $this->Ln(3);
    }
    
    // Page footer
    public function Footer()
    {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        
        // User info
        $user = $_SESSION['full_name'] ?? $_SESSION['username'] ?? 'Admin';
        $this->Cell(0, 5, 'Generated by: ' . $user . ' | Vehicle Management System', 0, 0, 'L');
        
        // Page number
        $this->Cell(0, 5, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, 0, 'R');
    }
    
    // Colored table method
    public function ColoredTable($header, $data)
    {
        // Set table header colors
        $this->SetFillColor(51, 122, 183); // Blue
        $this->SetTextColor(255); // White
        $this->SetDrawColor(128, 0, 0); // Dark red
        $this->SetLineWidth(0.3);
        $this->SetFont('helvetica', 'B', 9);
        
        // Column widths for landscape
        $w = array(18, 45, 35, 10, 40, 25, 40, 30, 25);
        
        // Header row
        foreach ($header as $i => $heading) {
            $this->Cell($w[$i], 8, $heading, 1, 0, 'C', 1);
        }
        $this->Ln();
        
        // Table data
        $this->SetFillColor(224, 235, 255); // Light blue
        $this->SetTextColor(0); // Black
        $this->SetFont('helvetica', '', 8);
        
        $fill = 0;
        $total_cost = 0;
        $record_count = 0;
        
        foreach ($data as $row) {
            $record_count++;
            $rowHeight = 0;
            
            // Calculate row height needed
            foreach ($row as $index => $column) {
                // For cost column, don't use htmlspecialchars on ₹ symbol
                if (strpos($column, '') === 0) {
                    $cellHeight = $this->getStringHeight($w[$index], $column);
                } else {
                    $cellHeight = $this->getStringHeight($w[$index], htmlspecialchars($column, ENT_QUOTES, 'UTF-8'));
                }
                $rowHeight = max($rowHeight, $cellHeight);
            }
            
            // Output row
            foreach ($row as $index => $column) {
                // Set alignment
                $align = 'L';
                if (in_array($index, array(0, 3))) { // Date, Type columns
                    $align = 'C';
                } elseif (in_array($index, array(5, 8))) { // KM, Cost columns
                    $align = 'R';
                }
                
                // For cost column, don't encode ₹ symbol
                if (strpos($column, '') === 0) {
                    $cellContent = $column;
                    // Extract cost for total
                    $cost = str_replace(array('', ','), '', $column);
                    $total_cost += (float)$cost;
                } else {
                    $cellContent = htmlspecialchars($column, ENT_QUOTES, 'UTF-8');
                }
                
                $this->MultiCell($w[$index], $rowHeight, $cellContent, 1, $align, $fill, 0);
            }
            $this->Ln();
            $fill = !$fill;
            
            // Check for page break
            if ($this->GetY() + $rowHeight > $this->getPageHeight() - $this->getBreakMargin()) {
                $this->AddPage();
                // Reprint header
                $this->SetFont('helvetica', 'B', 9);
                $this->SetFillColor(51, 122, 183);
                $this->SetTextColor(255);
                foreach ($header as $i => $heading) {
                    $this->Cell($w[$i], 8, $heading, 1, 0, 'C', 1);
                }
                $this->Ln();
                $this->SetFillColor(224, 235, 255);
                $this->SetTextColor(0);
                $this->SetFont('helvetica', '', 8);
            }
        }
        
        // Bottom line
        $this->Cell(array_sum($w), 0, '', 'T');
        
        // Summary section
        $this->Ln(10);
        $this->SetFont('helvetica', 'B', 11);
        $this->Cell(0, 8, 'REPORT SUMMARY', 0, 1, 'L');
        
        $this->SetFont('helvetica', '', 10);
        $this->Cell(60, 6, 'Total Services:', 0, 0, 'L');
        $this->Cell(40, 6, $record_count, 0, 1, 'L');
        
        $this->Cell(60, 6, 'Total Cost:', 0, 0, 'L');
        $this->Cell(40, 6, '' . number_format($total_cost, 2), 0, 1, 'L');
        
        if ($record_count > 0) {
            $this->Cell(60, 6, 'Average Cost:', 0, 0, 'L');
            $this->Cell(40, 6, '' . number_format($total_cost / $record_count, 2), 0, 1, 'L');
        }
    }
}

// Collect filters
$filters = array();
$filter_texts = array();

if (isset($_GET['search']) && !empty($_GET['search'])) {
    $filters['search'] = $_GET['search'];
    $filter_texts[] = 'Search: ' . $_GET['search'];
}

if (isset($_GET['vehicle_type']) && !empty($_GET['vehicle_type'])) {
    $filters['vehicle_type'] = $_GET['vehicle_type'];
    $filter_texts[] = 'Vehicle Type: ' . $_GET['vehicle_type'];
}

if (isset($_GET['service_type']) && !empty($_GET['service_type'])) {
    $filters['service_type'] = $_GET['service_type'];
    $filter_texts[] = 'Service Type: ' . $_GET['service_type'];
}

if (isset($_GET['from_date']) && !empty($_GET['from_date'])) {
    $filters['from_date'] = $_GET['from_date'];
    $filter_texts[] = 'From Date: ' . $_GET['from_date'];
}

if (isset($_GET['to_date']) && !empty($_GET['to_date'])) {
    $filters['to_date'] = $_GET['to_date'];
    $filter_texts[] = 'To Date: ' . $_GET['to_date'];
}

if (isset($_GET['vehicle_id']) && !empty($_GET['vehicle_id'])) {
    $vehicle_id = intval($_GET['vehicle_id']);
    $vehicle_sql = "SELECT * FROM vehicles WHERE id = $vehicle_id";
    $vehicle_result = $conn->query($vehicle_sql);
    if ($vehicle_result && $vehicle_result->num_rows > 0) {
        $vehicle = $vehicle_result->fetch_assoc();
        $filters['vehicle'] = $vehicle['make_model'] . ' (' . $vehicle['reg_number'] . ')';
        $filter_texts[] = 'Vehicle: ' . $vehicle['make_model'] . ' (' . $vehicle['reg_number'] . ')';
    } else {
        $filters['vehicle_id'] = $_GET['vehicle_id'];
        $filter_texts[] = 'Vehicle ID: ' . $_GET['vehicle_id'];
    }
}

// Build WHERE clause
$where = "WHERE 1=1";

if (isset($_GET['search']) && !empty($_GET['search'])) {
    $safe_search = $conn->real_escape_string($_GET['search']);
    $where .= " AND (s.service_type LIKE '%$safe_search%' OR s.description LIKE '%$safe_search%' OR v.make_model LIKE '%$safe_search%' OR v.reg_number LIKE '%$safe_search%' OR s.service_center_name LIKE '%$safe_search%' OR s.service_done_by LIKE '%$safe_search%')";
}

if (isset($_GET['vehicle_type']) && !empty($_GET['vehicle_type'])) {
    $safe_type = $conn->real_escape_string($_GET['vehicle_type']);
    $where .= " AND v.vehicle_type = '$safe_type'";
}

if (isset($_GET['service_type']) && !empty($_GET['service_type'])) {
    $safe_service_type = $conn->real_escape_string($_GET['service_type']);
    $where .= " AND s.service_type = '$safe_service_type'";
}

if (isset($_GET['from_date']) && !empty($_GET['from_date'])) {
    $where .= " AND s.service_date >= '" . $conn->real_escape_string($_GET['from_date']) . "'";
}

if (isset($_GET['to_date']) && !empty($_GET['to_date'])) {
    $where .= " AND s.service_date <= '" . $conn->real_escape_string($_GET['to_date']) . "'";
}

if (isset($_GET['vehicle_id']) && !empty($_GET['vehicle_id'])) {
    $where .= " AND s.vehicle_id = '" . intval($_GET['vehicle_id']) . "'";
}

$sql = "SELECT s.*, v.make_model, v.reg_number, v.vehicle_type, v.owner_name
        FROM services s
        JOIN vehicles v ON s.vehicle_id = v.id
        $where
        ORDER BY s.service_date DESC, s.service_time DESC";

$result = $conn->query($sql);

// Get summary statistics
$summary_sql = "SELECT 
               COUNT(*) as total_services, 
               SUM(cost) as total_cost,
               AVG(cost) as avg_cost
               FROM services s 
               JOIN vehicles v ON s.vehicle_id = v.id 
               $where";
$summary_result = $conn->query($summary_sql);
$summary = $summary_result->fetch_assoc();

// Create PDF
$pdf = new SERVICE_RECORDS_PDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set PDF info
$pdf->SetCreator('Vehicle Management System');
$pdf->SetAuthor($_SESSION['full_name'] ?? $_SESSION['username'] ?? 'Admin');
$pdf->SetTitle('Service Records Report');
$pdf->SetSubject('Service Records');

// Set filters and summary
$pdf->setFilters($filters);
$pdf->setSummary($summary);

// Set margins
$pdf->SetMargins(10, 35, 10); // Top margin for header

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 20);

// Add page
$pdf->AddPage();

// Prepare data
$data = array();

// Helper function to format text
$formatText = function($text, $maxLength = 20) {
    if (empty($text)) return '-';
    $text = htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
    return (strlen($text) > $maxLength) ? substr($text, 0, $maxLength) . '...' : $text;
};

if ($result && $result->num_rows > 0) {
    while($row = $result->fetch_assoc()) {
        $data[] = array(
            date('d-m-y', strtotime($row['service_date'])),
            $formatText($row['make_model'], 15),
            $formatText($row['reg_number'], 10),
            strtoupper(substr($row['vehicle_type'], 0, 1)),
            $formatText($row['service_type']),
            $row['running_km'] ? number_format($row['running_km']) : '-',
            $formatText($row['service_center_name'] ?? '-'),
            $formatText($row['service_done_by'] ?? '-'),
            '' . number_format($row['cost'], 2) // ₹ symbol added here
        );
    }
}

// Table headers
$header = array('Date', 'Vehicle', 'Reg No', 'T', 'Service Type', 'KM', 'Center', 'Done By', 'Cost');

// Generate table
if (!empty($data)) {
    $pdf->ColoredTable($header, $data);
} else {
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 10, 'NO SERVICE RECORDS FOUND', 0, 1, 'C');
    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 8, 'No service records match the selected criteria.', 0, 1, 'C');
}

// Add signature section
$pdf->Ln(15);
$pdf->SetFont('helvetica', '', 10);


// Add note
$pdf->SetFont('helvetica', 'I', 8);
$pdf->SetTextColor(100, 100, 100);
// $pdf->Cell(0, 10, 'Note: This is a computer generated report for service records.', 0, 1, 'C');

// Output PDF
$filename = 'service_records_' . date('Ymd_His') . '.pdf';
$pdf->Output($filename, 'D');

// Close connection
$conn->close();
exit();
?>