<?php
include '../config/database.php';
checkAuth();

$vehicle_id = $_GET['vehicle_id'] ?? '';

// Build WHERE clause
$where = "";
if (!empty($vehicle_id)) {
    $where = "WHERE s.vehicle_id = '" . intval($vehicle_id) . "'";
}

$sql = "SELECT s.*, v.make_model, v.reg_number, v.vehicle_type, v.owner_name
       FROM services s 
       JOIN vehicles v ON s.vehicle_id = v.id 
       $where 
       ORDER BY s.service_date DESC, s.service_time DESC";

$result = $conn->query($sql);

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="service_history_' . date('Y-m-d_H-i') . '.xls"');
?>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        table { border-collapse: collapse; width: 100%; }
        th { background-color: #4CAF50; color: white; padding: 8px; text-align: left; }
        td { border: 1px solid #ddd; padding: 8px; }
        .title { font-size: 18px; font-weight: bold; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="title">Service History Report</div>
    <div>Generated on: <?php echo date('d/m/Y H:i:s'); ?></div>
    <div>User: <?php echo $_SESSION['full_name'] ?? $_SESSION['username'] ?? 'Admin'; ?></div>
    
    <?php
    // Get vehicle details if specific vehicle is selected
    if (!empty($vehicle_id)) {
        $vehicle_sql = "SELECT * FROM vehicles WHERE id = $vehicle_id";
        $vehicle_result = $conn->query($vehicle_sql);
        if ($vehicle_result && $vehicle_result->num_rows > 0) {
            $vehicle = $vehicle_result->fetch_assoc();
            echo "<div><strong>Vehicle:</strong> " . $vehicle['make_model'] . " (" . $vehicle['reg_number'] . ")</div>";
        }
    }
    ?>
    <br>
    
    <table border="1">
        <tr>
            <th>Date</th>
            <th>Time</th>
            <?php if (empty($vehicle_id)): ?>
            <th>Vehicle</th>
            <th>Reg Number</th>
            <?php endif; ?>
            <th>Service Type</th>
            <th>Running KM</th>
            <th>Service Center</th>
            <th>Location</th>
            <th>Done By</th>
            <th>Cost (₹)</th>
            <th>Description</th>
            <th>Created By</th>
        </tr>
        <?php
        $total_cost = 0;
        $record_count = 0;
        
        if ($result && $result->num_rows > 0) {
            while($row = $result->fetch_assoc()) {
                $record_count++;
                $total_cost += $row['cost'];
                echo "<tr>
                        <td>" . date('d/m/Y', strtotime($row['service_date'])) . "</td>
                        <td>" . $row['service_time'] . "</td>";
                
                if (empty($vehicle_id)) {
                    echo "<td>" . htmlspecialchars($row['make_model']) . "</td>
                          <td>" . $row['reg_number'] . "</td>";
                }
                
                echo "<td>" . $row['service_type'] . "</td>
                      <td>" . ($row['running_km'] ? number_format($row['running_km']) : 'N/A') . "</td>
                      <td>" . htmlspecialchars($row['service_center_name'] ?? 'N/A') . "</td>
                      <td>" . htmlspecialchars($row['service_center_place'] ?? 'N/A') . "</td>
                      <td>" . htmlspecialchars($row['service_done_by'] ?? 'N/A') . "</td>
                      <td>" . number_format($row['cost'], 2) . "</td>
                      <td>" . htmlspecialchars(substr($row['description'] ?? 'No description', 0, 100)) . "</td>
                      <td>" . $row['created_by'] . "</td>
                    </tr>";
            }
            
            // Summary row
            echo "<tr style='background-color: #FFFFCC; font-weight: bold;'>
                    <td colspan='" . (empty($vehicle_id) ? 10 : 8) . "' style='text-align: right;'>Total Records: " . $record_count . "</td>
                    <td>₹" . number_format($total_cost, 2) . "</td>
                    <td colspan='2'></td>
                  </tr>";
        } else {
            echo "<tr><td colspan='" . (empty($vehicle_id) ? 12 : 10) . "' style='text-align: center; color: red; padding: 20px;'>No service records found</td></tr>";
        }
        ?>
    </table>
    
    <?php if ($record_count > 0): ?>
    <br>
    <div style="background-color: #f5f5f5; padding: 10px;">
        <strong>Summary:</strong><br>
        Total Services: <?php echo $record_count; ?><br>
        Total Cost: ₹<?php echo number_format($total_cost, 2); ?><br>
        Average Cost: ₹<?php echo number_format($total_cost / $record_count, 2); ?>
    </div>
    <?php endif; ?>
    
    <br>
    <div style="font-size: 11px; color: #666;">
        Generated by Vehicle Management System | <?php echo date('d/m/Y H:i:s'); ?>
    </div>
</body>
</html>